apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mste.fullname" . }}-api
  labels:
    {{- include "mste.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      {{- include "mste.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        {{- include "mste.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: api
          image: "{{ .Values.global.imageRegistry }}{{ .Values.image.api.repository }}:{{ .Values.image.api.tag }}"
          imagePullPolicy: {{ .Values.image.api.pullPolicy }}
          command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000",
                    "--workers", "4", "--loop", "uvloop"]
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: {{ .Values.secrets.existingSecret }}
          env:
            {{- range $k, $v := .Values.api.env }}
            - name:  {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
            - name:  HOST_PROJECT_PATH
              value: "/app"
          volumeMounts:
            - name:      scan-artifacts
              mountPath: /app/targets
          livenessProbe:  {{- toYaml .Values.api.livenessProbe  | nindent 12 }}
          readinessProbe: {{- toYaml .Values.api.readinessProbe | nindent 12 }}
          resources:      {{- toYaml .Values.api.resources       | nindent 12 }}
      volumes:
        - name: scan-artifacts
          persistentVolumeClaim:
            claimName: {{ include "mste.fullname" . }}-artifacts
